# Default values for gyeongsik-prd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default WordPress Site Info
name: argo-rollout-demo       # Kubernetes Namespace (A-z,0-9,'-')
app: argo-rollouts            # kubernetes App label 
domain: argo-rollout.stan-gyeong.shop     # Domain, e.g., mysite.com, mysite2.com, prd.anysite.com, etc.
nodepool: app-pool # Node Pool Name
storage: 50Gi      # Storage Size
ssd: false         # true=ssd, false=standard default
tls: true          # Set to 'true' for HTTPS/TLS/SSL



requestsMemory: "512Mi"
requestsCpu: "0.5"
limitsMemory: "2048Mi"
limitsCpu: "2"

replicaCount: 2
revisionHistoryLimit: 4
maxSurge: 30%
maxUnavailable: 30%
image:
  repository: argoproj/rollouts-demo 
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "blue"


imagePullSecrets: gyeongsik-secret 
nameOverride: "argo-rollouts"
fullnameOverride: "argo-rollouts"

serviceAccount:
  # Specifies whether a service account should be created
  create: false 
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true 
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  name: rollout-bg-active
  type: NodePort 
  port: 80

prservice:
  name: rollout-bg-preview
  type: NodePort
  port: 80 
  
ingress:
  enabled: true 
  className: ""
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: prd-gyeongsik-static
    # Associate the ingress with the certificate name
    #ingress.gcp.kubernetes.io/pre-shared-cert: "prd-gyeongsik-1,prd-gyeongsik-2"
    networking.gke.io/managed-certificates: argo-rollout-certificate
    networking.gke.io/v1beta1.FrontendConfig: prd-frontend-config
  
  rules:
    - host: argo-rollout.stan-gyeong.shop
      http:
        paths:
        - path: /*
          backend:
            serviceName: rollout-bg-active
            servicePort: 80
    # - host: prd-argo.gyeongsik-tet.shop
    #   http:
    #     paths:
    #     - path: /*
    #       backend:
    #         serviceName: rollout-bg-active
    #         servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: "2"
    memory: "2048Mi"
  requests:
    cpu: "0.5"
    memory: "1024Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 300    
  targetMemoryUtilizationPercentage: 200

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:

initCommand:
 - /bin/sh
 - -c
 - sleep 10

# postStartCommand:
#  - /bin/sh
#  - -c 
#  - |
#    sudo apt-get install curl;
#    mkdir -p /root/last_modify;  
#    curl -s https://storage.cloud.google.com/jgs-test-storage/date.sh | bash -s after;
#    echo "2022-12-18 04:31:28 PM" > /root/last_modify;



#preStopCommand:
#  - /bin/sh
#  - -c
#  - |
#    sleep 5;
#    nginx -s quit;